# Site settings
title: Blunut's Pages
author: Daehyun Park
email: dhp0102@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blunut.github.io" # the base hostname & protocol for your site
github_username:  blunut
facebook_username: Dae hyun Park
timezone : Asia/Seoul
encoding : utf-8
# collections:
# - my_collection
collections:
  my_collection:
    foo: bar
# collections:
#   - social: 
#     facebook_url: "http://www.facebook.com/daehyun.park.9041"
#     linkedin_url: "http://kr.linkedin.com/in/daehyunp"
#     github_url: "http://github.com/blunut"
#     google_plus_url: "http://plus.google.com/u/0/104968538208942334011/about"
#     twitter_url: "http://twitter.com/blunut12"
defaults:
  - scope:
      path: ""
      type: my_collection
    values:
      layout: default
# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: :compressed
