# Site settings
title: dhen-p's blog
name: dhen-p's blog
description: > # this means to ignore newlines until "author"
  Blogging about stuffs
  and development

email: dhp0102@gmail.com
baseurl: "/" # the subpath of your site, e.g. /blog/

domain_name: 'http://dhen-p.github.io'
github_username:  dhen-p
facebook_username: Dae hyun Park
timezone : Asia/Seoul
encoding : utf-8

# Build settings
markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
google_analytics: 'UA-XXXXXXXX-X'
sass:
    sass_dir: _sass
    style: :compressed

gems: [jekyll-paginate]

# Details for the RSS feed generator
url: "http://dhen-p.github.io" # the base hostname & protocol for your site
author: Daehyun Park
author_description: >
  이것저것 공부중인 학생개발자 입니다.
  블로그는 처음이네요. https://dhen-p.github.io/about
