# Site settings
title: dhparkz blog
name: dhparkz blog
description: > # this means to ignore newlines until "author"
  Blogging about stuffs
  and development

email: dhp0102@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/

domain_name: 'http://dhparkz.github.io'
github_username:  dhparkz
facebook_username: Dae hyun Park
timezone : Asia/Seoul
encoding : utf-8

# Build settings
markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
google_analytics: 'UA-XXXXXXXX-X'
sass:
    sass_dir: _sass
    style: :compressed

gems: [jekyll-paginate]

# Details for the RSS feed generator
url: "http://dhparkz.github.io" # the base hostname & protocol for your site
author: Daehyun Park
author_description: >
  https://dhparkz.github.io/about
